server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newsfeed
    username: root
    password: efqan1999

  jpa:
    generate-ddl: true
    show-sql: true

#  liquibase:
#    enabled: true
#    change-log: classpath:/db/changelog/master.yaml
